[[azbntple tpl="/src/common/fancybox3/js/core.js" ]]
[[azbntple tpl="/src/common/fancybox3/js/guestures.js" ]]
[[azbntple tpl="/src/common/fancybox3/js/media.js" ]]
[[azbntple tpl="8/src/common/fancybox3/js/fullscreen.js" ]]
[[azbntple tpl="8/src/common/fancybox3/js/hash.js" ]]
[[azbntple tpl="8/src/common/fancybox3/js/slideshow.js" ]]
[[azbntple tpl="8/src/common/fancybox3/js/thumbs.js" ]]